### ISSUE TITLE
执行evaluate时出错

### ISSUE THREAD

**Issue by wjh-scut** [Git-123-Hub/maddpg-pettingzoo-pytorch#1]
在训练完成后，执行evaluate时出错，如下：
`Traceback (most recent call last):
  File "D:\PyCharm 2021.2.2\code\maddpg-pettingzoo-pytorch-master\evaluate.py", line 41, in <module>
    frame_list.append(Image.fromarray(env.render(mode='rgb_array')))
TypeError: aec_to_parallel_wrapper.render() got an unexpected keyword argument 'mode'`
请问一下，这个是什么原因啊？是gym或者pettingzoo的版本不对吗？

**Comment by Git-123-Hub** [comment]
建议你先检查一下各个包的版本是否与`requirements.txt`中相同

另外pyglet应当使用`1.5.x`的版本，我用的是`1.5.24`

**Comment by wjh-scut** [comment]
> 建议你先检查一下各个包的版本是否与`requirements.txt`中相同
> 
> 另外pyglet应当使用`1.5.x`的版本，我用的是`1.5.24`

好的，非常感谢。我更换了gym版本为0.9.5就可以了。

**Comment by lyjxxr** [comment]
usage: evaluate.py [-h] [--episode-num EPISODE_NUM]
                   [--episode-length EPISODE_LENGTH]
                   {simple_adversary_v2,simple_spread_v2,simple_tag_v2} folder
evaluate.py: error: the following arguments are required: env_name, folder
这个是什么原因

**Comment by AZ1229-forever** [comment]
> usage: evaluate.py [-h] [--episode-num EPISODE_NUM] [--episode-length EPISODE_LENGTH] {simple_adversary_v2,simple_spread_v2,simple_tag_v2} folder evaluate.py: error: the following arguments are required: env_name, folder 这个是什么原因

我也是这个问题
